### ISSUE TITLE
bugfix(offers): selection of checkboxes of the new offers are selected together.

### ISSUE THREAD

**Issue by AdrianAlzamoraG** [futureleadersupc/waw-frontend-vue#51] opened 2022-06-27 22:05 UTC
### Describe the bug

After creating more than 1 offer, when you select each one of them, the checkboxes of all the new offers that have just been added are automatically activated.

### Steps to reproduce the behavior

1. Go to 'Jobs section'
2. Add 2 offers
3. select a checkbox of one of the last offers added.

### Expected behavior

Select only one offer

### Screenshots

![image](https://user-images.githubusercontent.com/89112826/176043481-8b36bad6-f2c5-4b0b-8029-53b136d915dc.png)

**Comment by dalbitresb12** [comment] 2022-06-28 02:48
As discussed with @amenes12, apparently this is working as intended. This happens due to the fact that the fake API returns the same ID for new items. So when you select any of those items with the same ID the data table selects all of them.

Closing as working as intended.

**Closed by dalbitresb12** 2022-06-28 02:48 UTC
Labels: bug, wontfix
